services:
  - type: web
    name: springboot-crud
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:escueladb
      - key: SPRING_DATASOURCE_USERNAME
        value: tecsup
      - key: SPRING_DATASOURCE_PASSWORD
        value: tecsup
